spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/accountdb
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      customerService:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s

    instances:
      customerService:
        baseConfig: default